WEBSITE_URL = "https://www.lusha.com/company-search/wholesale/30/united-kingdom/12/page/24/"
# WEBSITE_URL = "https://www.lusha.com/company-search/wholesale/30/united-kingdom/12/"
# WEBSITE_URL = "https://www.bheta.co.uk/supplier-search/"
# WEBSITE_URL = "https://www.confex.ltd.uk/suppliers_list.asp"
# WEBSITE_URL = "https://www.esources.co.uk/suppliers.php"
# WEBSITE_URL = "https://www.great.gov.uk/international/trade/search/?q=&industries=CLOTHING_FOOTWEAR_AND_FASHION&industries=CREATIVE_AND_MEDIA&industries=FOOD_AND_DRINK&industries=GIFTWARE_JEWELLERY_AND_TABLEWARE&industries=HOUSEHOLD_GOODS_FURNITURE_AND_FURNISHINGS&industries=RETAIL_AND_LUXURY&industries=TEXTILES_INTERIOR_TEXTILES_AND_CARPETS"
# WEBSITE_URL = "https://www.thewholesaler.co.uk/"

obj = {
    "Audio & Staging": [
        "AV Rental & Production",
        "DJ",
        "Lighting",
        "Rigging",
        "Sound Systems",
        "Special Effects",
    ],
    "Beverage Services": [
        "Bartenders ",
        "Beverage Catering",
        "Mobile Bars",
    ],
    "Cakes & Dessert": [
        "Custom Cakes",
        "Dessert Stations",
        "Pastry Chefs",
    ],
    "Catering": [
        "Catering for Special Dietary Needs",
        "Food Trucks",
        "Full-Service Catering",
        "Private Chef",
    ],
    "Cleaning": [
        "Event Cleanup",
        "Sanitation Services",
    ],
    "Destination Management": [
        "Hotel & Venue Coordination",
        "Local Tours",
        "Transportation",
    ],
    "Entertainment": [
        "Experiential Entertainment",
        "Group Activities",
        "Live Activation",
        "Live Music",
        "Performance Art",
    ],
    "Experiential Agency": [
        "Brand Experience Management",
        "Event Planning",
        "Marketing Activations",
    ],
    "Experiential Design": [
        "Custom Installations",
        "Event Themes",
        "Interactive Experiences",
        "Virtual Reality",
    ],
    "Experiential Tech": [
        "Augmented Reality",
        "Interactive Kiosks",
    ],
    "Fabrication": [
        "Custom Builds",
        "Set Design",
        "Stage Construction",
    ],
    "Florals & Design": [
        "Event Decor",
        "Floral Arrangements",
    ],
    "Gifts & Swag": [
        "Custom Branded Gifts",
        "Event Swag Bags",
        "Promotional Products",
    ],
    "Health Screening": [
        "Health and Safety Checks",
        "On-Site Medical Services",
    ],
    "Installation Art": [
        "Interactive Art",
        "Temporary Art Installations",
    ],
    "Internet Services": [
        "On-Site Networking",
        "Tech Support",
        "Wi-Fi Solutions",
    ],
    "Invites & Graphic Design": [
        "Event Invitations",
        "Graphic Design Services",
        "Print Materials",
    ],
    "Rentals": [
        "Furniture Rentals",
        "Linens",
        "Tableware",
        "Tenting",
    ],
    "Security & Permits": [
        "Crowd Management",
        "Event Security",
        "Permit Acquisition",
    ],
    "Signage & Printing": [
        "Banners",
        "Directional Signage",
        "Event Signage",
    ],
    "Speaker": [
        "Industry Experts",
        "Keynote Speakers",
        "Public Speakers",
    ],
    "Staffing": [
        "Event Staff",
        "Temporary Labor",
        "Volunteers",
    ],
    "Transportation & Parking": [
        "Parking Management",
        "Shuttle Services",
        "Valet Services",
    ],
    "Videography": [
        "Event Videography",
        "Live Streaming",
        "Video Editing",
    ],
    "Venues": [
        "Booking Services",
        "Event Venues",
        "Indoor Venues (e.g., conference centers, hotels)",
        "Outdoor Venues (e.g., parks, stadiums)",
        "Site Visits",
        "Unique Venues (e.g., historic buildings, museums)",
        "Venue Coordination",
        "Venue Management",
    ]
}

categories = [
    "Audio & Staging",
    "Beverage Services",
    "Cakes & Dessert",
    "Catering",
    "Cleaning",
    "Destination Management",
    "Entertainment",
    "Experiential Agency",
    "Experiential Design",
    "Experiential Tech",
    "Fabrication",
    "Florals & Design",
    "Gifts & Swag",
    "Health Screening",
    "Installation Art",
    "Internet Services",
    "Invites & Graphic Design",
    "Rentals",
    "Security & Permits",
    "Signage & Printing",
    "Speaker",
    "Staffing",
    "Transportation & Parking",
    "Videography",
    "Venues"
]

subCategories = [
    "AV Rental & Production",
    "Augmented Reality",
    "Banners",
    "Bartenders ",
    "Beverage Catering",
    "Booking Services",
    "Brand Experience Management",
    "Catering for Special Dietary Needs",
    "Crowd Management",
    "Custom Branded Gifts",
    "Custom Builds",
    "Custom Cakes",
    "Custom Installations",
    "DJ",
    "Dessert Stations",
    "Directional Signage",
    "Event Cleanup",
    "Event Decor",
    "Event Invitations",
    "Event Planning",
    "Event Security",
    "Event Signage",
    "Event Staff",
    "Event Swag Bags",
    "Event Themes",
    "Event Venues",
    "Event Videography",
    "Experiential Entertainment",
    "Floral Arrangements",
    "Food Trucks",
    "Full-Service Catering",
    "Furniture Rentals",
    "Graphic Design Services",
    "Group Activities",
    "Health and Safety Checks",
    "Hotel & Venue Coordination",
    "Indoor Venues (e.g., conference centers, hotels)",
    "Industry Experts",
    "Interactive Art",
    "Interactive Experiences",
    "Interactive Kiosks",
    "Keynote Speakers",
    "Lighting",
    "Linens",
    "Live Activation",
    "Live Music",
    "Live Streaming",
    "Local Tours",
    "Marketing Activations",
    "Mobile Bars",
    "On-Site Medical Services",
    "On-Site Networking",
    "Outdoor Venues (e.g., parks, stadiums)",
    "Parking Management",
    "Pastry Chefs",
    "Performance Art",
    "Permit Acquisition",
    "Print Materials",
    "Private Chef",
    "Promotional Products",
    "Public Speakers",
    "Rigging",
    "Sanitation Services",
    "Set Design",
    "Shuttle Services",
    "Site Visits",
    "Sound Systems",
    "Special Effects",
    "Stage Construction",
    "Tableware",
    "Tech Support",
    "Temporary Art Installations",
    "Temporary Labor",
    "Tenting",
    "Transportation",
    "Unique Venues (e.g., historic buildings, museums)",
    "Valet Services",
    "Venue Coordination",
    "Venue Management",
    "Video Editing",
    "Virtual Reality",
    "Volunteers",
    "Wi-Fi Solutions"
]
